/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export default function Valentin(props) {
	const { nodes } = useGLTF("/valentin.glb")

	return (
		<group {...props} dispose={null}>
			<mesh
				name="body"
				castShadow
				receiveShadow
				geometry={nodes.body.geometry}
				position={[0, -0.38, 0]}
			>
				<meshStandardMaterial color={"red"} />
			</mesh>
			<mesh
				name="rightLeg"
				castShadow
				receiveShadow
				geometry={nodes.rightLeg.geometry}
				position={[-0.584, -2.272, 0]}
			>
				<meshStandardMaterial color={"black"} />
			</mesh>
			<mesh
				name="leftLeg"
				castShadow
				receiveShadow
				geometry={nodes.leftLeg.geometry}
				position={[0.477, -1.839, 0]}
			>
				<meshStandardMaterial color={"black"} />
			</mesh>
			<mesh
				name="rightHand"
				castShadow
				receiveShadow
				geometry={nodes.rightHand.geometry}
				position={[-1.44, -0.449, 0]}
				rotation={[0, 0, 2.781]}
			>
				<meshStandardMaterial color={"white"} />
			</mesh>
			<mesh
				name="leftHand"
				castShadow
				receiveShadow
				geometry={nodes.leftHand.geometry}
				position={[1.578, -0.894, 0]}
				rotation={[0, 0, -2.781]}
			>
				<meshStandardMaterial color={"white"} />
			</mesh>
			<mesh
				name="eye"
				castShadow
				receiveShadow
				geometry={nodes.eye.geometry}
				position={[0, 0.156, 0.607]}
			>
				<meshStandardMaterial color={"white"} />
			</mesh>
			<mesh
				name="rightArm"
				castShadow
				receiveShadow
				geometry={nodes.rightArm.geometry}
				position={[-1.44, -0.449, 0]}
				rotation={[0, 0, 2.781]}
			>
				<meshStandardMaterial color={"black"} />
			</mesh>
			<mesh
				name="leftArm"
				castShadow
				receiveShadow
				geometry={nodes.leftArm.geometry}
				position={[1.578, -0.894, 0]}
				rotation={[0, 0, -2.781]}
			>
				<meshStandardMaterial color={"black"} />
			</mesh>
		</group>
	)
}

useGLTF.preload("/valentin.glb")
